# Generated by Django 6.0.3 on 2026-03-14

"""Add Stripe-related subscription fields to the Profile model."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Persist billing identifiers and subscription lifecycle data."""

    dependencies = [
        ('builder', '0003_alter_cv_title_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
