# Generated by Django 6.0.3 on 2026-03-14 17:59

"""Add richer profile fields to CV records for better letter quality."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Introduce optional summary, phone number, and location fields."""

    dependencies = [
        ('builder', '0004_profile_billing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cv',
            name='summary',
            field=models.TextField(
                blank=True,
                help_text=(
                    'A short personal statement about your career goals.'
                ),
            ),
        ),
    ]
